# Generated by Django 5.2.12 on 2026-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię i Nazwisko')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_me_images/', verbose_name='Zdjęcie profilowe')),
            ],
            options={
                'verbose_name': 'O mnie',
                'verbose_name_plural': 'O mnie',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię i Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('link_instagram', models.URLField(blank=True, null=True, verbose_name='Link do Instagrama')),
                ('link_facebook', models.URLField(blank=True, null=True, verbose_name='Link do Facebooka')),
            ],
            options={
                'verbose_name': 'Moje dane kontaktowe',
                'verbose_name_plural': 'Moje dane kontaktowe',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('status', models.CharField(choices=[('New', 'Nowa'), ('Read', 'Przeczytana'), ('Finished', 'Zakończona')], default='New', max_length=20, verbose_name='Status wiadomości')),
            ],
            options={
                'verbose_name': 'Wiadomość od klientów',
                'verbose_name_plural': 'Wiadomości od klientów',
            },
        ),
    ]
