# Generated by Django 5.2.12 on 2026-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instagram_images/', verbose_name='Zdjęcie')),
                ('instagram_url', models.URLField(blank=True, help_text='Wklej tutaj link do posta na IG', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Składniki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('optional_information', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('wartosc_energetyczna', models.CharField(blank=True, max_length=30, null=True, verbose_name='Wartość energetyczna (kcal)')),
                ('bialko', models.CharField(blank=True, max_length=300, null=True, verbose_name='Białko (g)')),
                ('weglowodany', models.CharField(blank=True, max_length=30, null=True, verbose_name='Węglowodany (g)')),
                ('sol', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sól (g)')),
                ('blonnik', models.CharField(blank=True, max_length=30, null=True, verbose_name='Błonnik (g)')),
                ('index_glikemiczny', models.CharField(blank=True, max_length=30, null=True, verbose_name='Indeks glikemiczny')),
                ('ladunek_glikemiczny', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ładunek glikemiczny')),
                ('zelazo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Żelazo (mg)')),
                ('wapn', models.CharField(blank=True, max_length=30, null=True, verbose_name='Wapń (mg)')),
            ],
        ),
    ]
